CREATE TABLE IF NOT EXISTS table_metiers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
);

INSERT INTO table_metiers (nom) VALUES 
('Abatteur'), ('Accompagnateur de voyage'), ('Acheteur'), ('Actuaire'), ('Adjoint administratif'), 
('Administrateur de base de données'), ('Agent d''escale'), ('Agent d''entretien'), 
('Agent de sécurité'), ('Agent immobilier'), ('Agriculteur'), ('Agronome'), ('Aide-soignant'), 
('Ambulancier'), ('Analyste financier'), ('Animateur'), ('Antiquaire'), ('Apiculteur'), 
('Archéologue'), ('Architecte'), ('Architecte d''intérieur'), ('Archiviste'), ('Artisan'), 
('Assistant de direction'), ('Assistant social'), ('Assureur'), ('Astrophysicien'), ('Avocat'), 
('Boucher'), ('Boulanger'), ('Bibliothécaire'), ('Bijoutier'), ('Biologiste'), ('Bûcheron'), 
('Cadreur'), ('Carreleur'), ('Carrossier'), ('Cartographe'), ('Caissier'), ('Chanteur'), 
('Charpentier'), ('Chauffeur de taxi'), ('Chauffeur-livreur'), ('Chargé d''affaires'), 
('Chargé de communication'), ('Chaudronnier'), ('Chef de cuisine'), ('Chef de projet'), 
('Chercheur'), ('Chirurgien'), ('Chirurgien-dentiste'), ('Clerc de notaire'), ('Coiffeur'), 
('Comptable'), ('Comédien'), ('Community manager'), ('Conducteur de travaux'), ('Conseiller d''orientation'), 
('Conseiller financier'), ('Consultant'), ('Contrôleur aérien'), ('Contrôleur de gestion'), 
('Cordonnier'), ('Correcteur'), ('Courtier'), ('Cuisinier'), ('Data scientist'), ('Designer industriel'), 
('Dessinateur'), ('Détective privé'), ('Développeur informatique'), ('Diététicien'), ('Directeur artistique'), 
('Directeur des ressources humaines'), ('Dominotier'), ('Doreur'), ('Ébéniste'), ('Économiste'), 
('Écrivain'), ('Éditeur'), ('Électricien'), ('Éleveur'), ('Employé de banque'), ('Entraîneur sportif'), 
('Épicier'), ('Ergonome'), ('Esthéticien'), ('Étancheur'), ('Facteur'), ('Fleuriste'), ('Forgeron'), 
('Fromager'), ('Gardien de la paix'), ('Géomètre'), ('Gérant de magasin'), ('Graphiste'), 
('Greffier'), ('Guide touristique'), ('Horticulteur'), ('Huissier de justice'), ('Illustrateur'), 
('Infirmier'), ('Informaticien'), ('Ingénieur civil'), ('Ingénieur du son'), ('Ingénieur en aéronautique'), 
('Inspecteur du travail'), ('Instituteur'), ('Interprète'), ('Jardinier'), ('Journaliste'), 
('Juge'), ('Kinésithérapeute'), ('Libraire'), ('Maçon'), ('Magasinier'), ('Magistrat'), 
('Maître d''hôtel'), ('Manipulateur radio'), ('Maquilleur'), ('Maraîcher'), ('Menuisier'), 
('Météorologue'), ('Miroitier'), ('Moniteur d''auto-école'), ('Monteur vidéo'), ('Musicien'), 
('Notaire'), ('Nutritionniste'), ('Oculiste'), ('Opticien'), ('Orthophoniste'), ('Ostéopathe'), 
('Paléontologue'), ('Pâtissier'), ('Paysagiste'), ('Peintre en bâtiment'), ('Pharmacien'), 
('Photographe'), ('Pilote de ligne'), ('Plombier'), ('Poissonnier'), ('Policier'), ('Pompier'), 
('Professeur'), ('Psychologue'), ('Puéricultrice'), ('Réacteur nucléaire'), ('Rédacteur web'), 
('Relieur'), ('Responsable logistique'), ('Sage-femme'), ('Serrurier'), ('Sociologue'), 
('Sommelier'), ('Soudeur'), ('Sténotypiste'), ('Styliste'), ('Tailleur de pierre'), ('Tapissier'), 
('Technicien de surface'), ('Traducteur'), ('Urbaniste'), ('Vendeur'), ('Vétérinaire'), 
('Vigneron'), ('Webdesigner'), ('Zoologiste');
