CREATE TABLE IF NOT EXISTS table_sports (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
);

INSERT INTO table_sports (nom) VALUES 
('Aéromodélisme'), ('Aéronautique'), ('Aïkido'), ('Alpinisme'), ('Apnée'), ('Athlétisme'), ('Aviron'), 
('Badminton'), ('Ball-trap'), ('Ballon au poing'), ('Baseball'), ('Basketball'), ('Basque de pelote'), 
('Battu de tambourin'), ('Biathlon'), ('Billard'), ('Bobsleigh'), ('Bodyboard'), ('Boomerang'), 
('Boule lyonnaise'), ('Bowling'), ('Boxe anglaise'), ('Boxe chinoise'), ('Boxe française'), 
('Boxe thaïlandaise'), ('Canoë-kayak'), ('Canyoning'), ('Course d''orientation'), ('Course landaise'), 
('Course camarguaise'), ('Cricket'), ('Croquet'), ('Curling'), ('Cyclisme sur route'), 
('Cyclisme sur piste'), ('Cyclocross'), ('Danse sportive'), ('Deltaplane'), ('Disque-golf'), 
('Double dutch'), ('Échecs'), ('Équitation'), ('Escalade'), ('Escrime'), ('Esport'), 
('Faustball'), ('Fistball'), ('Floorball'), ('Football'), ('Football américain'), ('Football australien'), 
('Football de table'), ('Football gaélique'), ('Force athlétique'), ('Frisbee'), ('Futsal'), 
('Golf'), ('Gymnastique artistique'), ('Gymnastique rythmique'), ('Haltérophilie'), ('Handball'), 
('Handisport'), ('Hapkido'), ('Hockey sur gazon'), ('Hockey sur glace'), ('Horse-ball'), 
('Hurasan'), ('Iaidō'), ('Javelot tir sur cible'), ('Jeu de paume'), ('Ju-jitsu'), ('Judo'), 
('Karaté'), ('Karting'), ('Kendo'), ('Kenpō'), ('Kick-boxing'), ('Kin-ball'), ('Kitesurf'), 
('Korfbal'), ('Longue paume'), ('Luge de course'), ('Lutte'), ('Motocyclisme'), ('Motonautisme'), 
('Muay-thaï'), ('Natation'), ('Natation synchronisée'), ('Nid-de-poule'), ('Omnikin'), ('Paddle'), 
('Pancrace'), ('Parachutisme'), ('Parapente'), ('Patinage artistique'), ('Patinage de vitesse'), 
('Patinage synchronisé'), ('Pelote basque'), ('Pentathlon moderne'), ('Pétanque'), ('Planche à voile'), 
('Plongée sous-marine'), ('Plongeon'), ('Polo'), ('Qi gong'), ('Quidditch'), ('Rafting'), 
('Rallye'), ('Randonnée pédestre'), ('Raquettes à neige'), ('Ring hockey'), ('Rink hockey'), 
('Roller derby'), ('Roller in line hockey'), ('Roller skating'), ('Rugby à VII'), ('Rugby à XIII'), 
('Rugby à XV'), ('Sambo'), ('Sambo de combat'), ('Sanda'), ('Saut à ski'), ('Sauvetage sportif'), 
('Savate'), ('Sextant'), ('Skateboard'), ('Ski acrobatique'), ('Ski alpin'), ('Ski de fond'), 
('Ski de vitesse'), ('Ski nautique'), ('Ski nordique'), ('Ski rando'), ('Slalom'), ('Snowboard'), 
('Spéléologie'), ('Sport boules'), ('Sport d''entreprise'), ('Sport en milieu rural'), ('Sport pour tous'), 
('Sport travailliste'), ('Sport universitaire'), ('Squash'), ('Sumo'), ('Surf'), ('Taekwondo'), 
('Taï-chi-chuan'), ('Tango'), ('Tennis'), ('Tennis de table'), ('Tir à l''arc'), ('Tir sportif'), 
('Trampoline'), ('Triathlon'), ('Trot attelé'), ('Trot monté'), ('Twirling bâton'), ('Ultimate'), 
('Ulm'), ('Varaigne'), ('Vovinam viet vo dao'), ('VTT'), ('Wakeboard'), ('Water-polo'), 
('Wingfoil'), ('Wushu'), ('Yachting'), ('Yoseikan budo'), ('Zen'), ('Zumba');
