DROP TABLE IF EXISTS table_vegetaux;

CREATE TABLE table_vegetaux (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
);

INSERT INTO table_vegetaux (nom) VALUES 
('Abricot'), ('Ail'), ('Airelle'), ('Amande'), ('Ananas'), ('Artichaut'), ('Asperge'), 
('Aubergine'), ('Avocat'), ('Banane'), ('Betterave'), ('Blette'), ('Brocoli'), 
('Brugnon'), ('Cacahuète'), ('Canneberge'), ('Carambole'), ('Carotte'), ('Cassis'), 
('Céleri'), ('Cerise'), ('Champignon'), ('Châtaigne'), ('Chayote'), ('Chou'), 
('Chou de Bruxelles'), ('Chou-fleur'), ('Chou-rave'), ('Ciboulette'), ('Citron'), 
('Citron vert'), ('Citrouille'), ('Clémentine'), ('Coing'), ('Concombre'), 
('Courge'), ('Courgette'), ('Cresson'), ('Datte'), ('Échalote'), ('Endive'), 
('Épinard'), ('Fenouil'), ('Fève'), ('Figue'), ('Fraise'), ('Framboise'), 
('Fruit de la passion'), ('Gombo'), ('Goyave'), ('Grenade'), ('Groseille'), 
('Haricot vert'), ('Kaki'), ('Kiwi'), ('Laitue'), ('Lentille'), ('Litchi'), 
('Mâche'), ('Maïs'), ('Mandarine'), ('Mangue'), ('Manioc'), ('Melon'), 
('Mirabelle'), ('Mûre'), ('Myrtille'), ('Navet'), ('Nectarine'), ('Nèfle'), 
('Noisette'), ('Noix'), ('Noix de coco'), ('Noix de cajou'), ('Oignon'), 
('Orange'), ('Orange sanguine'), ('Oseille'), ('Pamplemousse'), ('Panais'), 
('Papaye'), ('Pastèque'), ('Patate douce'), ('Pâtisson'), ('Pêche'), 
('Petit pois'), ('Physalis'), ('Pignon de pin'), ('Piment'), ('Pissenlit'), 
('Pistache'), ('Poire'), ('Poireau'), ('Pois chiche'), ('Pois gourmand'), 
('Poivron'), ('Pomme'), ('Pomme de terre'), ('Potiron'), ('Prune'), 
('Quetsche'), ('Radis'), ('Radis noir'), ('Raisin'), ('Rhubarbe'), 
('Romanesco'), ('Roquette'), ('Salsifis'), ('Tomate'), ('Topinambour');

commit;